version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo
    network_mode: host
    restart: always
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin  
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=admin
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    
  api:
    build: .
    container_name: api
    network_mode: host
    volumes:
      - .:/opt/app
      - /opt/app/node_modules
    ports:
      - 3000:3000
    restart: always
    command: npm run start
    env_file:
      - .env
    depends_on:
      - mongo

volumes:
  mongo-data: