name: Publish Docker

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish to registry
        run: |
          docker build . --tag ghcr.io/thesafatem/top-api:latest
          docker run ghcr.io/thesafatem/top-api:latest
          docker push ghcr.io/thesafatem/top-api:latest
