name: Publish Docker

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          registry: docker.pkg.github.com
          name: docker.pkg.github.com/thesafatem/top-api/top-api
          username: ${{ secrets.DOCKER_USERNAME }}
          passwords: ${{ secrets.DOCKER_PASSWORD }}
          tags: 'develop'
